# Site settings
title: Alpha Project
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Alpha Project is a UBC Club in which members collectively work together to create a single open source software engineering project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
